config/routes.rb
Rails.application.routes.draw do
  get 'answers/new'

  root 'static_pages#home'
  get '/help',   to: 'static_pages#help'
  get '/about',  to: 'static_pages#about'
  get '/signup',  to: 'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :categories
  resources :lessons do
    resources :answers, only: [:new]
  end
  namespace :admin do 
    resources :users, only: [:index]
    resources :categories do
      resources :words
    end
  end
end 

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :wordchoices
  has_one :lesson_word
  accepts_nested_attributes_for :wordchoices, allow_destroy: true
  validates :name,  presence: true
  
  def answer
    self.wordchoices.where(correct: true).name
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  
  def index
    @category = Category.find(params[:category_id])
    @words = Word.all
    @wordchoices = Wordchoice.all
  end
  
  def new
    category = Category.find(params[:category_id])
    @word = category.words.build
    4.times { @word.wordchoices.build }
  end
  
  def create
    category = Category.find(params[:category_id])
    @word = category.words.new(word_params)
    if @word.save
      flash[:success] = "Successfully Create!"
      redirect_to admin_category_words_path(@word)
    else
      render 'new'
    end
  end
  
  def show
    @word = Word.find(params[:id])
  end
  
  def edit
    @word = Word.find(params[:id])
  end
  
  def update
    @word = Word.find(params[:id])
    if @word.update_attributes(word_params)
      flash[:success] = "Word Updated!"
      redirect_to admin_category_words_path
    else
      render 'edit'
    end
  end
  
  
  private
  
  def word_params
    params.require(:word).permit(:name,
                                 wordchoices_attributes: [:id, :name, :correct])
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  
  def new
  end
  
  def create
  end
  
  def index
    category = Category.find(params[:category_id])
    @word = category.words.build
    @wordchoices = Wordchoice.all
  end
  
  
end

app/helpers/admin/categories/words_helper.rb
module Admin::Categories::WordsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/words/_word.html.erb
<tr>
  <th width="180"><%= word.name %></th>
  <th width="180"><%= word.answer %></th>
  <th width="180"><%= link_to "edit", edit_admin_category_word_path) %>/<%= link_to("delete") %></th>
</tr>

app/views/admin/words/index.html.erb
<%= provide(:title, "All words") %>
<h1><%= @category.title %></h1>
<div class="row">
 <div class="col-md-6 col-md-offset-3">
  <div class="row index">
    <table class="table table-bordered index-table">
        <tbody>
            <tr>
             <th width="180">Word</th>
             <th width="180">Answer</th>
             <th width="180">Settings</th>
            </tr>
            <%= render @words %>
        </tbody>
    </table>
  </div>
 </div>
</div>

app/views/admin/words/new.html.erb
<%= provide(:button_text, "Save words") %>
<div class="row">
   <div class="col-md-6 col-md-offset-3">
<%= form_for(@word, url: admin_category_words_path) do |f| %>
Words:
   <li>
     <%= f.label :name %>
     <%= f.text_field :name %>
   </li>
   <%= f.fields_for :wordchoices do |choices_form| %>
   Word choice:
     <li>
       <%= choices_form.label :name %>
       <%= choices_form.text_field :name %>
       <%= choices_form.label :correct %>
       <%= choices_form.check_box :correct, {}, true, false %>
     </li>
   <% end %>
   <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>
  </div>
</div>