config/routes.rb
Rails.application.routes.draw do
  get 'answers/new'

  root 'static_pages#home'
  get '/help',   to: 'static_pages#help'
  get '/about',  to: 'static_pages#about'
  get '/signup',  to: 'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :categories
  resources :lessons do
    resources :answers, only: [:new]
  end
  namespace :admin do 
    resources :users, only: [:index]
    resources :categories do
      resources :words
    end
  end
end 

app/models/category.rb
class Category < ApplicationRecord
  has_many :words
  has_many :users, through: :lessons
  validates :title, presence: true
  validates :description, presence: true, length: {minimum: 3 }
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :admin_user
  
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end
  
  def show
    @category = Category.find(params[:id])
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Successfully Create!"
      redirect_to new_admin_category_word_path(@category)
    else
      render 'new'
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:success] = "Category Updated!"
      redirect_to admin_categories_path
    else
      render 'edit'
    end
  end
  
  def destroy
    Category.find(params[:id]).destroy
    flash[:success] = "Successfully deleted"
    redirect_to admin_categories_path
  end
  
  
  private
  
  def category_params
    params.require(:category).permit(:title, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :logged_in_user
  before_action :admin_user
  
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end
  
  def show
    @category = Category.find(params[:id])
  end
  
  def create
  end

  def edit
  end
end

app/helpers/admin/categories/words_helper.rb
module Admin::Categories::WordsHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<tr>
  <th><%= link_to category.title, admin_category_words_path(category) %></th>
  <th><%= category.description %></th>
  <th><%= link_to "edit", edit_admin_category_path(category) %>/<%= link_to "delete", category, method: :delete, 
                                                data: { confirm: "You sure?" }  %></th>
</tr>

app/views/admin/categories/_form.html.erb
    <%= form_for([:admin, @category]) do |f| %>
      
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      
      <%= f.label :description %>
      <%= f.text_area :description, col: 40, rows: 5 %>
      
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>

app/views/admin/categories/edit.html.erb
<% provide(:title, "Edit Category") %>
<% provide(:button_text, "Save changes") %>
<h1>Update Category</h1>
<div class="row">
  <div class="col-md-6 com-md-offset-3">
  <%= render 'form' %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<%= provide(:title, "All categories") %>
<div class="row">
 <div class="col-md-6 col-md-offset-3">
  <div class="row index">
    <table class="table table-bordered index-table">
        <tbody>
            <tr>
             <th>title</th>
             <th>description</th>
             <th>Settings</th>
            </tr>
            <%= render @categories %>
        </tbody>
    </table>
  </div>
 </div>
</div>

app/views/admin/categories/new.html.erb
<%= provide(:title, "CreateCategory") %>
<%= provide(:button_text, 'Create') %>
<h1>Create new Category</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/categories/show.html.erb
<%= provide(:title, @category.title) %>

<h1><%= @category.title %></h1>
<h2><%= @category.description %></h2>